version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - game_1630

x-django-build: &django-build
  build:
    context: .
    dockerfile: ./Dockerfile.prod

services:
  celery:
    <<: *django-build
    container_name: game_1630-cc01
    restart: unless-stopped
    command: bash -c "celery -A game_1630 worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  celery-beat:
    <<: *django-build
    container_name: game_1630-cb01
    restart: unless-stopped
    command: bash -c "celery -A game_1630 worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  django:
    <<: *django-build
    container_name: game_1630-dc01
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - game_1630_static_volume:/code/static
      - game_1630_media_volume:/code/media
    depends_on:
      - redis
    <<: *common


  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    container_name: game_1630-nc01
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - game_1630_static_volume:/code/static
      - game_1630_media_volume:/code/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    <<: *common

  redis:
    image: redis:6.2-buster
    container_name: game_1630-rc01
    restart: unless-stopped
    volumes:
      - game_1630_redis_data:/data
    <<: *common

networks:
  game_1630:
    driver: bridge

volumes:
  game_1630_redis_data:
  game_1630_static_volume:
  game_1630_media_volume:
