version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - game_1630

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: game_1630-dc01
    command: bash -c "python manage.py runserver 0.0.0.0:8005"
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - ./:/code
      - game_1630_static_volume:/code/static
      - game_1630_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common


  postgres:
    image: postgres:13.3-alpine
    container_name: game_1630-pc01
    env_file:
      - .env
    ports:
      - "5439:5439"
    volumes:
      - game_1630_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-alpine
    container_name: game_1630-rc01
    volumes:
      - game_1630_redis_data:/data
    <<: *common

networks:
  game_1630:
    driver: bridge

volumes:
  game_1630_postgres_data:
  game_1630_redis_data:
  game_1630_static_volume:
  game_1630_media_volume:
