version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - game_1630

x-django-build: &django-build
  build:
    context: .
    dockerfile: ./Dockerfile.dev

services:
  celery:
    <<: *django-build
    container_name: game_1630-cc01
    command: bash -c "celery -A game_1630 worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  celery-beat:
    <<: *django-build
    container_name: game_1630-cb01
    command: bash -c "celery -A game_1630 worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  django:
    <<: *django-build
    container_name: game_1630-dc01
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - game_1630_static_volume:/code/static
      - game_1630_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    image: mher/flower:0.9.7
    container_name: game_1630-fc01
    command:
      [
        "flower",
        "--broker=redis://redis:6379/0",
        "--broker_api=redis://redis:6379/0",
        "--port=5555",
      ]
    ports:
      - "5555:5555"
    <<: *common

  postgres:
    image: postgres:13.3-alpine
    container_name: game_1630-pc01
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - game_1630_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-alpine
    container_name: game_1630-rc01
    volumes:
      - game_1630_redis_data:/data
    <<: *common

networks:
  game_1630:
    driver: bridge

volumes:
  game_1630_postgres_data:
  game_1630_redis_data:
  game_1630_static_volume:
  game_1630_media_volume:
