version: "3.4"

services:
  cr:
    build:
      context: .
      dockerfile: ./Dockerfile.cr
    container_name: game_1630-cr01
    command: bash -c "/code/scripts/cr.sh"
    volumes:
      - ./:/code
